# Site settings
title: 
header-img: img/home-bg.png
email: lizzie.sorin@hotmail.fr
copyright_name: lizzie92869
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  lizzie92869
learn_profile: lizzie92869
email_username: lizzie.sorin@hotmail.fr

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
